# Generated by Django 6.0.1 on 2026-02-18 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_campaignresponse_job_function'),
        ('tenancy', '0014_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardactionplan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company'),
        ),
    ]
